### ISSUE TITLE
UPNP port mapping is gone from router after a few seconds

### ISSUE THREAD

**Issue by aabluedragon** [paullouisageneau/node-portmapping#1]
Hello,

using method `createMapping`, creates a mapping in my router (I see it in gateway UI), but disappears a few seconds later.

Any way to work around that?

Thanks

**Comment by aabluedragon** [comment]
I found a solution, as long as I keep a variable reference to the mapper object, the port stays up.

```
nodePortMapping.init();
nodePortMapping.createMapping({....})
```

Then I simply make sure the reference to var `nodePortMapping` stays in memory, and port stays up.
Once I release the variable reference, or call `cleanup()` it is gone.

So I guess it's the intended behavior.

**Comment by paullouisageneau** [comment]
Indeed, the underlying library libplum cleans up the mapping on destruction, which happens if the object is garbage collected. Therefore, you need to ensure you keep a reference.
